---
name: build

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  core:
    strategy:
      matrix:
        go-version: [1.16.x, 1.17.x]
        platform: [ubuntu-latest]
    name: Build
    runs-on: ${{ matrix.platform }}
    env:
      GOBIN: /home/runner/.local/bin
    steps:
    - name: Install Go
      uses: actions/setup-go@v1
      with:
        go-version: ${{ matrix.go-version }}
      id: go
    - name: Check out code into the Go module directory
      uses: actions/checkout@v2
    - name: Install Go modules
      run: |
        mkdir -p .coverage
        make dep
    - name: Run tests
      run: |
        # go test -v -coverprofile=.coverage/coverage.out ./*.go
        # go tool cover -html=.coverage/coverage.out -o .coverage/coverage.html
        # go test -covermode=count -coverprofile=.coverage/coverage.out ./*.go
        # go tool cover -func=.coverage/coverage.out | grep -v 100
        make linter
        make
    # - name: Upload coverage report
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: Test Coverage Report
    #    path: .coverage/coverage.html
